#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: container compliant runAsUser" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_container_compliant_runAsUser.json \
      -s test_data/test_container_compliant_runAsUser-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: container violating runAsUser" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_container_violating_runAsUser.json \
      -s test_data/test_container_violating_runAsUser-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"Container is potentially running as root. Please check spec.template.spec.containers[0].securityContext.runAsUser to see if the UID is correct."* ]]
}
