#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

# TODO: this policy needs a hand-written counter-case.

@test "accept: k8s instance exists" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_k8s_instance_exists.json \
      -s test_data/test_k8s_instance_exists-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}
