#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: trusted domain" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_trusted_domain.json \
      -s test_data/test_trusted_domain-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: untrusted domain" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_untrusted_domain.json \
      -s test_data/test_untrusted_domain-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The GitRepository 'example' targets an untrusted domain. Found: 'https://github.com/untrusted-org/repo'"* ]]
}
