#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: patch annotation matches provider" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_patch_annotation_matches_provider.json \
      -s test_data/test_patch_annotation_matches_provider-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: patch annotation does not match provider" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_patch_annotation_does_not_match_provider.json \
      -s test_data/test_patch_annotation_does_not_match_provider-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The Kustomization 'example' must have a patch annotation that matches the provider 'aws'. Annotation 'eks.amazonaws.com/role-arn' not found"* ]]
}
