#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: key value exists" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_key_value_exists.json \
      -s test_data/test_key_value_exists-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: host not allowed" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_host_not_allowed.json \
      -s test_data/test_host_not_allowed-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"You have specified hosts: '[console.gcp.dev.magalix.com]'; detected 'console.example.com'"* ]]
}
