#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: k8s part of exists" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_k8s_part_of_exists.json \
      -s test_data/test_k8s_part_of_exists-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: k8s part of missing" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_k8s_part_of_missing.json \
      -s test_data/test_k8s_part_of_missing-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"Missing 'app.kubernetes.io/part-of' label"* ]]
}
