#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid resource not suspended" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_resource_not_suspended.json \
      -s test_data/test_valid_resource_not_suspended-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid resource suspended" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_resource_suspended.json \
      -s test_data/test_invalid_resource_suspended-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The resource 'invalid-helm-release' of kind 'HelmRelease' must not be suspended."* ]]
}
