#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid helm repo url" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_helm_repo_url.json \
      -s test_data/test_valid_helm_repo_url-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid helm repo url" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_helm_repo_url.json \
      -s test_data/test_invalid_helm_repo_url-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The HelmRepository URL must be from one of the allowed domains '[example.com]'; found 'https://another-example.com/charts'"* ]]
}
