#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: prune enabled compliance" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_prune_enabled_compliance.json \
      -s test_data/test_prune_enabled_compliance-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: prune enabled violation" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_prune_enabled_violation.json \
      -s test_data/test_prune_enabled_violation-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The 'spec.prune' field in the Kustomization object must be set to 'true', but found 'false'"* ]]
}
