apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: kubewarden-policies
  annotations:
    hauler.dev/certificate-oidc-issuer: https://token.actions.githubusercontent.com
spec:
  images:
    - name: ghcr.io/kubewarden/policies/allow-privilege-escalation-psp:v1.0.13
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/allow-privilege-escalation-psp-policy/v1.0.13
    - name: ghcr.io/kubewarden/policies/allowed-fsgroups-psp:v1.0.12
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/allowed-fsgroups-psp-policy/v1.0.12
    - name: ghcr.io/kubewarden/policies/allowed-proc-mount-types-psp:v1.0.15
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/allowed-proc-mount-types-psp-policy/v1.0.15
    - name: ghcr.io/kubewarden/policies/annotations:v0.1.11
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/annotations-policy/v0.1.11
    - name: ghcr.io/kubewarden/policies/apparmor-psp:v1.0.14
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/apparmor-psp-policy/v1.0.14
    - name: ghcr.io/kubewarden/policies/capabilities-psp:v1.0.13
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/capabilities-psp-policy/v1.0.13
    - name: ghcr.io/kubewarden/policies/cel-policy:v1.6.3
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/cel-policy/v1.6.3
    - name: ghcr.io/kubewarden/policies/container-resources:v1.3.6
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/container-resources-policy/v1.3.6
    - name: ghcr.io/kubewarden/policies/deprecated-api-versions:v1.0.11
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/deprecated-api-versions-policy/v1.0.11
    - name: ghcr.io/kubewarden/policies/disallow-service-loadbalancer:v1.0.14
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/disallow-service-loadbalancer-policy/v1.0.14
    - name: ghcr.io/kubewarden/policies/disallow-service-nodeport:v1.0.0
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/disallow-service-nodeport-policy/v1.0.0
    - name: ghcr.io/kubewarden/policies/do-not-expose-admission-controller-webhook-services:v1.1.8
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/do-not-expose-admission-controller-webhook-services-policy/v1.1.8
    - name: ghcr.io/kubewarden/policies/echo:v0.1.19
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/echo/v0.1.19
    - name: ghcr.io/kubewarden/policies/env-variable-secrets-scanner:v1.0.15
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/env-variable-secrets-scanner-policy/v1.0.15
    - name: ghcr.io/kubewarden/policies/environment-variable-policy:v3.0.7
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/environment-variable-policy/v3.0.7
    - name: ghcr.io/kubewarden/policies/flexvolume-drivers-psp:v1.0.17
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/flexvolume-drivers-psp-policy/v1.0.17
    - name: ghcr.io/kubewarden/policies/high-risk-service-account:v0.1.9
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/high-risk-service-account-policy/v0.1.9
    - name: ghcr.io/kubewarden/policies/host-namespaces-psp:v1.1.11
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/host-namespaces-psp-policy/v1.1.11
    - name: ghcr.io/kubewarden/policies/hostpaths-psp:v1.1.10
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/hostpaths-psp-policy/v1.1.10
    - name: ghcr.io/kubewarden/policies/image-cve-policy:v0.6.3
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/image-cve-policy/v0.6.3
    - name: ghcr.io/kubewarden/policies/ingress:v1.0.11
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/ingress-policy/v1.0.11
    - name: ghcr.io/kubewarden/policies/kyverno-dsl:v0.1.11
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/kyverno-dsl-policy/v0.1.11
    - name: ghcr.io/kubewarden/policies/labels:v0.1.10
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/labels-policy/v0.1.10
    - name: ghcr.io/kubewarden/policies/namespace-label-propagator:v1.0.12
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/namespace-label-propagator-policy/v1.0.12
    - name: ghcr.io/kubewarden/policies/ns-policyserver-mapper:v0.1.3
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/ns-policyserver-mapper-policy/v0.1.3
    - name: ghcr.io/kubewarden/policies/persistentvolumeclaim-storageclass-policy:v1.1.8
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/persistentvolumeclaim-storageclass-policy/v1.1.8
    - name: ghcr.io/kubewarden/policies/pod-ndots:v1.0.12
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/pod-ndots-policy/v1.0.12
    - name: ghcr.io/kubewarden/policies/pod-privileged:v1.0.13
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/pod-privileged-policy/v1.0.13
    - name: ghcr.io/kubewarden/policies/pod-runtime:v1.0.12
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/pod-runtime-class-policy/v1.0.12
    - name: ghcr.io/kubewarden/policies/priority-class-policy:v1.1.8
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/priority-class-policy/v1.1.8
    - name: ghcr.io/kubewarden/policies/probes:v1.0.7
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/probes-policy/v1.0.7
    - name: ghcr.io/kubewarden/policies/psa-label-enforcer:v1.0.14
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/psa-label-enforcer-policy/v1.0.14
    - name: ghcr.io/kubewarden/policies/rancher-project-propagate-labels:v0.1.7
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/rancher-project-propagate-labels/v0.1.7
    - name: ghcr.io/kubewarden/policies/rancher-project-quotas-namespace-validator:v1.0.13
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/rancher-project-quotas-namespace-validator/v1.0.13
    - name: ghcr.io/kubewarden/policies/readonly-root-filesystem-psp:v1.0.13
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/readonly-root-filesystem-psp-policy/v1.0.13
    - name: ghcr.io/kubewarden/policies/runtime-enforcer:v0.1.4
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/runtime-enforcer-policy/v0.1.4
    - name: ghcr.io/kubewarden/policies/safe-annotations:v1.0.7
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/safe-annotations-policy/v1.0.7
    - name: ghcr.io/kubewarden/policies/safe-labels:v1.0.12
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/safe-labels-policy/v1.0.12
    - name: ghcr.io/kubewarden/policies/seccomp-psp:v1.0.15
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/seccomp-psp-policy/v1.0.15
    - name: ghcr.io/kubewarden/policies/selinux-psp:v1.1.2
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/selinux-psp-policy/v1.1.2
    - name: ghcr.io/kubewarden/policies/share-pid-namespace-policy:v1.0.14
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/share-pid-namespace-policy/v1.0.14
    - name: ghcr.io/kubewarden/policies/sysctl-psp:v1.0.14
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/sysctl-psp-policy/v1.0.14
    - name: ghcr.io/kubewarden/policies/trusted-repos:v2.1.4
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/trusted-repos-policy/v2.1.4
    - name: ghcr.io/kubewarden/policies/unique-ingress-policy:v1.0.12
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/unique-ingress-policy/v1.0.12
    - name: ghcr.io/kubewarden/policies/unique-service-selector-policy:v1.0.13
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/unique-service-selector-policy/v1.0.13
    - name: ghcr.io/kubewarden/policies/user-group-psp:v1.1.5
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/user-group-psp-policy/v1.1.5
    - name: ghcr.io/kubewarden/policies/verify-image-signatures:v1.0.11
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/verify-image-signatures/v1.0.11
    - name: ghcr.io/kubewarden/policies/volumemounts:v1.0.11
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/volumeMounts-policy/v1.0.11
    - name: ghcr.io/kubewarden/policies/volumes-psp:v1.1.10
      certificate-identity-regexp: https://github.com/kubewarden/policies/.github/workflows/release.yml@refs/tags/volumes-psp-policy/v1.1.10
