#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: values file valid" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_values_file_valid.json \
      -s test_data/test_values_file_valid-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: values file invalid" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_values_file_invalid.json \
      -s test_data/test_values_file_invalid-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The HelmChart 'my-helm-chart' must reference values files in the format 'values(-xxx)?.yaml'; found 'invalid-values-file.yaml'"* ]]
}
