#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: key value exists" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_key_value_exists.json \
      -s test_data/test_key_value_exists-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: no labels" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_no_labels.json \
      -s test_data/test_no_labels-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The resource has no labels. Required label 'owner:tony2' not found."* ]]
}
