#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: cosign verification valid" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_cosign_verification_valid.json \
      -s test_data/test_cosign_verification_valid-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: cosign verification invalid" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_cosign_verification_invalid.json \
      -s test_data/test_cosign_verification_invalid-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The OCIRepository must provide cosign verification and reference a secret containing the Cosign public keys of trusted authors in '.tgz' extension"* ]]
}
