#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid endpoint domain" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_endpoint_domain.json \
      -s test_data/test_valid_endpoint_domain-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid endpoint domain" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_endpoint_domain.json \
      -s test_data/test_invalid_endpoint_domain-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The Bucket 'invalid-bucket' has an endpoint domain that is not in the trusted domains list: [example.com trusted.com]; found 'minio.untrusted.com'"* ]]
}
