#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: secure connection compliance" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_secure_connection_compliance.json \
      -s test_data/test_secure_connection_compliance-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: insecure connection violation" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_insecure_connection_violation.json \
      -s test_data/test_insecure_connection_violation-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"Insecure connections are not allowed for Bucket objects. Please set 'spec.insecure' to 'false' or remove the field."* ]]
}
