#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid reconcile interval" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_reconcile_interval.json \
      -s test_data/test_valid_reconcile_interval-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid reconcile interval lower bound" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_reconcile_interval_lower_bound.json \
      -s test_data/test_invalid_reconcile_interval_lower_bound-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The resource 'invalid-helm-release' of kind 'HelmRelease' reconcile interval must be at least 30 seconds; found 20"* ]]
}
