#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid bucket region" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_bucket_region.json \
      -s test_data/test_valid_bucket_region-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid bucket region" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_bucket_region.json \
      -s test_data/test_invalid_bucket_region-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The Bucket 'invalid-bucket' region must be one of the approved regions: [us-west-2 us-east-1]; found 'eu-west-1'"* ]]
}
