#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: ignore suffixes present" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_ignore_suffixes_present.json \
      -s test_data/test_ignore_suffixes_present-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: ignore suffixes missing" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_ignore_suffixes_missing.json \
      -s test_data/test_ignore_suffixes_missing-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The GitRepository 'example' must only include allowed suffixes in the ignore field. Allowed suffixes: [.md .txt]"* ]]
}
