#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: allowed exclude label" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_allowed_exclude_label.json \
      -s test_data/test_allowed_exclude_label-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: ingress from wrong namespace" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_ingress_from_wrong_namespace.json \
      -s test_data/test_ingress_from_wrong_namespace-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"spec.ingress[0].from[0].namespaceSelector does not match the namespace ns1;"* ]]
}
