#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: allowed configmaps" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_allowed_configmaps.json \
      -s test_data/test_allowed_configmaps-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: unallowed configmaps" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_unallowed_configmaps.json \
      -s test_data/test_unallowed_configmaps-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The HelmRelease 'test-helm-release' is using an unallowed ConfigMap 'unallowed-configmap' in valuesFrom."* ]]
}
