#!/usr/bin/env python3
"""Generate the end-to-end tests of a Rego policy from its unit tests.

A Rego policy of this repository keeps its unit tests in `policy_test.rego` or
under `tests/`. Every `test_*` rule builds a `testcase` object that holds the
settings of the policy and the reviewed Kubernetes object:

    test_something {
      testcase = {
        "parameters": { ... },
        "review": { "object": { ... } }
      }
      count(violation) == 0 with input as testcase
    }

This script reads those rules through the AST that `opa parse` gives, and it
writes:

  * `test_data/<rule name>.json`, the admission request that wraps the object
  * `test_data/<rule name>-settings.json`, the settings, when the test gives any
  * `e2e.bats`, with one accept test and one reject test

It runs `kwctl` once for each of the two cases. The run proves that the
generated request gives the same verdict as the unit test, and it gives the
rejection message that the test then asserts.

Usage:

    hack/generate-rego-e2e.py policies/FluxBucketInsecure
    hack/generate-rego-e2e.py --all

The script needs `opa`, `kwctl`, `make` and `bats`. Use the OPA version that
the CI pins in `.github/actions/install-dependencies`.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

# The plural of a kind, for the fields `resource` and `requestResource` of the
# admission request. No policy of this repository reads those fields, but a
# well-formed request helps a reader of the fixture.
IRREGULAR_PLURALS = {
    "Endpoints": "endpoints",
    "Ingress": "ingresses",
    "NetworkPolicy": "networkpolicies",
    "PodSecurityPolicy": "podsecuritypolicies",
    "Policy": "policies",
    "PriorityClass": "priorityclasses",
    "StorageClass": "storageclasses",
}


MARKER = "# Generated by hack/generate-rego-e2e.py. Do not edit by hand."
NO_OP = "No-op. TODO: add end-to-end tests"


class GeneratorError(Exception):
    """A policy that the script cannot handle."""


class SkipPolicy(Exception):
    """A policy that the script must leave alone."""


def run(command, **kwargs):
    return subprocess.run(command, capture_output=True, text=True, **kwargs)


def opa_parse(files):
    """Return the AST of the given Rego files.

    OPA 1.0 and later read Rego v1 by default, and every policy of this
    repository uses v0. The second attempt adds the compatibility flag.
    """
    result = run(["opa", "parse", "--format", "json", *files])
    if result.returncode != 0:
        result = run(["opa", "parse", "--format", "json", "--v0-compatible", *files])
    if result.returncode != 0:
        raise GeneratorError(f"opa parse failed: {result.stderr.strip()}")
    return json.loads(result.stdout)


def term_to_value(term):
    """Convert one AST term into the Python value that it denotes."""
    kind = term["type"]
    if kind in ("string", "number", "boolean", "null"):
        return term.get("value")
    if kind == "array":
        return [term_to_value(item) for item in term["value"]]
    if kind == "set":
        return [term_to_value(item) for item in term["value"]]
    if kind == "object":
        return {term_to_value(pair[0]): term_to_value(pair[1]) for pair in term["value"]}
    if kind == "var" and term["value"] in ("true", "false", "null"):
        return {"true": True, "false": False, "null": None}[term["value"]]
    raise GeneratorError(f"cannot convert a term of type {kind}")


def operator_name(term):
    """Return the name of the operator of an expression, or None."""
    if term.get("type") != "ref":
        return None
    head = term["value"][0]
    if head.get("type") != "var":
        return None
    return head["value"]


def read_test_rules(policy_dir):
    """Return the test cases of a policy, in the order of the source."""
    files = sorted(str(path) for path in policy_dir.glob("tests/*.rego"))
    files += sorted(str(path) for path in policy_dir.glob("*_test.rego"))
    if not files:
        raise GeneratorError("the policy has no unit test")

    cases = []
    for path in files:
        ast = opa_parse([path])
        for rule in ast.get("rules") or []:
            name = rule.get("head", {}).get("name", "")
            if not name.startswith("test_"):
                continue
            case = read_one_rule(rule, name)
            if case is not None:
                case["file"] = Path(path).stem
                cases.append(case)

    # Two test files of a policy can hold a rule of the same name. The name of
    # the fixture then carries the name of the file as well, so that the second
    # case does not overwrite the first.
    seen = {}
    for case in cases:
        seen[case["name"]] = seen.get(case["name"], 0) + 1
    for case in cases:
        if seen[case["name"]] > 1:
            case["fixture"] = f"{case['name']}-{case['file']}"
        else:
            case["fixture"] = case["name"]
    return cases


def read_one_rule(rule, name):
    """Return the testcase and the expected violation count of one test rule."""
    testcase = None
    expected = None

    for expression in rule.get("body") or []:
        terms = expression.get("terms")
        if not isinstance(terms, list) or len(terms) < 3:
            continue
        operator = operator_name(terms[0])

        # testcase = { ... }
        if (
            operator in ("eq", "assign")
            and terms[1].get("type") == "var"
            and terms[1].get("value") == "testcase"
            and terms[2].get("type") == "object"
        ):
            testcase = term_to_value(terms[2])
            continue

        # count(violation) == <number>
        if operator in ("eq", "equal", "gt", "gte"):
            call, number = terms[1], terms[2]
            if call.get("type") == "call" and number.get("type") == "number":
                if operator_name(call["value"][0]) == "count":
                    expected = number["value"]

    if testcase is None or expected is None:
        return None
    return {"name": name, "testcase": testcase, "expected": expected}


def plural_of(kind):
    if kind in IRREGULAR_PLURALS:
        return IRREGULAR_PLURALS[kind]
    lower = kind.lower()
    if lower.endswith("y"):
        return lower[:-1] + "ies"
    if lower.endswith(("s", "x", "ch", "sh")):
        return lower + "es"
    return lower + "s"


def admission_request(obj):
    """Wrap a Kubernetes object in the admission request that kwctl reads."""
    api_version = obj.get("apiVersion", "v1")
    if "/" in api_version:
        group, version = api_version.split("/", 1)
    else:
        group, version = "", api_version
    kind = obj.get("kind", "Pod")
    metadata = obj.get("metadata") or {}

    group_version_kind = {"group": group, "version": version, "kind": kind}
    group_version_resource = {"group": group, "version": version, "resource": plural_of(kind)}

    return {
        "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
        "kind": group_version_kind,
        "resource": group_version_resource,
        "requestKind": group_version_kind,
        "requestResource": group_version_resource,
        "name": metadata.get("name", "test"),
        "namespace": metadata.get("namespace", "default"),
        "operation": "CREATE",
        "userInfo": {
            "username": "kubernetes-admin",
            "groups": ["system:masters", "system:authenticated"],
        },
        "object": obj,
        "oldObject": None,
        "dryRun": False,
        "options": None,
    }


def pick_cases(cases):
    """Return one accept case and one reject case, or None for a missing one."""
    accept = next((case for case in cases if case["expected"] == 0), None)
    reject = next((case for case in cases if case["expected"] == 1), None)
    if reject is None:
        reject = next((case for case in cases if case["expected"] > 0), None)
    return accept, reject


def write_fixture(policy_dir, case):
    """Write the request and the settings of one case. Return their paths."""
    testcase = case["testcase"]
    review = testcase.get("review") or {}
    obj = review.get("object")
    if not isinstance(obj, dict):
        raise GeneratorError(f"{case['name']} has no review.object")

    test_data = policy_dir / "test_data"
    test_data.mkdir(exist_ok=True)

    request_path = test_data / f"{case['fixture']}.json"
    request_path.write_text(json.dumps(admission_request(obj), indent=2) + "\n")

    settings_path = None
    parameters = testcase.get("parameters")
    if isinstance(parameters, dict) and parameters:
        settings_path = test_data / f"{case['fixture']}-settings.json"
        settings_path.write_text(json.dumps(parameters, indent=2) + "\n")

    return request_path, settings_path


def kwctl_run(policy_dir, request_path, settings_path):
    """Run the policy against one request. Return the parsed response."""
    command = [
        "kwctl",
        "run",
        "-e",
        "gatekeeper",
        "annotated-policy.wasm",
        "-r",
        str(request_path.relative_to(policy_dir)),
    ]
    if settings_path is not None:
        command += ["-s", str(settings_path.relative_to(policy_dir))]

    result = run(command, cwd=policy_dir)
    if result.returncode != 0:
        raise GeneratorError(f"kwctl failed: {result.stderr.strip()}")

    last_line = [line for line in result.stdout.splitlines() if line.strip()][-1]
    return json.loads(last_line)


def build_policy(policy_dir):
    result = run(["make", "-s", "annotated-policy.wasm"], cwd=policy_dir)
    if result.returncode != 0:
        raise GeneratorError(f"make annotated-policy.wasm failed: {result.stderr.strip()}")


def bats_block(title, case, request_path, settings_path, message):
    """Return one @test block."""
    lines = [f'@test "{title}" {{']
    lines.append("  run kwctl run -e gatekeeper annotated-policy.wasm \\")
    if settings_path is None:
        lines.append(f"      -r test_data/{request_path.name}")
    else:
        lines.append(f"      -r test_data/{request_path.name} \\")
        lines.append(f"      -s test_data/{settings_path.name}")
    lines += [
        "",
        "  # this prints the output when one of the checks below fails",
        '  echo "output = ${output}"',
        "",
        '  [ "$status" -eq 0 ]',
    ]
    if message is None:
        lines.append("""  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]""")
    else:
        lines.append("""  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]""")
        lines.append(f'  [[ "$output" == *{json.dumps(message)}* ]]')
    lines.append("}")
    return "\n".join(lines)


def generate(policy_dir, force=False):
    """Generate the fixtures and the e2e.bats of one policy."""
    bats_path = policy_dir / "e2e.bats"
    if bats_path.exists() and not force:
        content = bats_path.read_text()
        if MARKER not in content and NO_OP not in content:
            raise SkipPolicy("the policy has hand-written end-to-end tests")

    cases = read_test_rules(policy_dir)
    accept, reject = pick_cases(cases)
    if accept is None and reject is None:
        raise GeneratorError("no usable test case")

    build_policy(policy_dir)

    blocks = []
    problems = []

    if accept is not None:
        request_path, settings_path = write_fixture(policy_dir, accept)
        response = kwctl_run(policy_dir, request_path, settings_path)
        if response.get("allowed") is not True:
            problems.append(f"the accept case {accept['name']} is rejected by the policy")
        else:
            blocks.append(
                bats_block(
                    f"accept: {accept['name'][len('test_'):].replace('_', ' ')}",
                    accept,
                    request_path,
                    settings_path,
                    None,
                )
            )

    if reject is not None:
        request_path, settings_path = write_fixture(policy_dir, reject)
        response = kwctl_run(policy_dir, request_path, settings_path)
        status = response.get("status") or {}
        message = status.get("message")
        if status.get("code") == 500 or (message or "").startswith("internal server error"):
            problems.append(
                f"the reject case {reject['name']} makes the policy fail at runtime: {message}"
            )
            message = None
        elif response.get("allowed") is not False or not message:
            problems.append(f"the reject case {reject['name']} is accepted by the policy")
            message = None
        if message is not None:
            blocks.append(
                bats_block(
                    f"reject: {reject['name'][len('test_'):].replace('_', ' ')}",
                    reject,
                    request_path,
                    settings_path,
                    message,
                )
            )

    if not blocks:
        raise GeneratorError("; ".join(problems) or "no usable test case")

    header = ["#!/usr/bin/env bats", "", MARKER, ""]
    if accept is None or reject is None or problems:
        header.append("# TODO: this policy needs a hand-written counter-case.")
        header.append("")
    bats_path.write_text("\n".join(header) + "\n" + "\n\n".join(blocks) + "\n")

    return problems


def rego_policies(root):
    for makefile in sorted(root.glob("policies/*/Makefile")):
        if os.path.islink(makefile) and os.readlink(makefile) == "../Makefile.p-rego":
            yield makefile.parent


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("policy", nargs="*", help="policy directory")
    parser.add_argument("--all", action="store_true", help="every Rego policy of the repository")
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite an e2e.bats that was edited by hand",
    )
    arguments = parser.parse_args()

    for tool in ("opa", "kwctl", "make"):
        if shutil.which(tool) is None:
            sys.exit(f"{tool} is not in the PATH")

    root = Path(__file__).resolve().parent.parent
    if arguments.all:
        directories = list(rego_policies(root))
    else:
        directories = [Path(name).resolve() for name in arguments.policy]
    if not directories:
        sys.exit("give a policy directory, or --all")

    failed = {}
    warned = {}
    skipped = {}
    for directory in directories:
        try:
            problems = generate(directory, force=arguments.force)
            if problems:
                warned[directory.name] = problems
            print(f"ok      {directory.name}")
        except SkipPolicy as reason:
            skipped[directory.name] = str(reason)
            print(f"skip    {directory.name}: {reason}")
        except GeneratorError as error:
            failed[directory.name] = str(error)
            print(f"ERROR   {directory.name}: {error}")

    generated = len(directories) - len(failed) - len(skipped)
    print(f"\ngenerated: {generated}, skipped: {len(skipped)}, errors: {len(failed)}")
    if warned:
        print("\npolicies that need a hand-written case:")
        for name, problems in sorted(warned.items()):
            print(f"  - {name}: {'; '.join(problems)}")
    if failed:
        print("\npolicies that the script could not handle:")
        for name, error in sorted(failed.items()):
            print(f"  - {name}: {error}")


if __name__ == "__main__":
    main()
