#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: blocked ingress rule" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_blocked_ingress_rule-allowed_ingress_rule_test.json \
      -s test_data/test_blocked_ingress_rule-allowed_ingress_rule_test-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: blocked ingress rule" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_blocked_ingress_rule-blocked_ingress_rule_test.json \
      -s test_data/test_blocked_ingress_rule-blocked_ingress_rule_test-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"CIDR block should contain '10.244.120.70/31'; but [10.244.120.70/32] was detected"* ]]
}
