#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: namespace match valid" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_namespace_match_valid.json \
      -s test_data/test_namespace_match_valid-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: namespace match invalid" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_namespace_match_invalid.json \
      -s test_data/test_namespace_match_invalid-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The HelmRelease 'my-helm-release' storageNamespace and targetNamespace must match; found storageNamespace 'storage-namespace' and targetNamespace 'target-namespace'"* ]]
}
