#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: patches required enabled no violation" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_patches_required_enabled_no_violation.json \
      -s test_data/test_patches_required_enabled_no_violation-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: patches required enabled violation" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_patches_required_enabled_violation.json \
      -s test_data/test_patches_required_enabled_violation-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The 'spec.patches' field in a Kustomization object must have values based on the policy input"* ]]
}
