#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: container runAsNonRoot true" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_container_runAsNonRoot_true.json \
      -s test_data/test_container_runAsNonRoot_true-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: container missing securityContext pod incomplete" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_container_missing_securityContext_pod_incomplete.json \
      -s test_data/test_container_missing_securityContext_pod_incomplete-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"Container missing spec.template.spec.containers[0].securityContext.runAsNonRoot while Pod spec.template.spec.securityContext.runAsNonRoot is not defined as well."* ]]
}
