#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid target namespace" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_target_namespace.json \
      -s test_data/test_valid_target_namespace-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid target namespace" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_target_namespace.json \
      -s test_data/test_invalid_target_namespace-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The Kustomization 'invalid-kustomization' targetNamespace must be one of the allowed target namespaces: allowed-namespace; found 'disallowed-namespace'"* ]]
}
