#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: allowed domain" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_allowed_domain.json \
      -s test_data/test_allowed_domain-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: disallowed domain" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_disallowed_domain.json \
      -s test_data/test_disallowed_domain-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The OCIRepository 'example' must be from an allowed organization domain. Found: 'oci://ghcr.io/disallowed-org/repo'"* ]]
}
