#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid image tag" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_image_tag.json \
      -s test_data/test_valid_image_tag-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid image tag" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_image_tag.json \
      -s test_data/test_invalid_image_tag-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The Kustomization 'example' spec.images entry for image 'podinfo' must comply with image tag/semver reference standards. Invalid tag: 'invalid-tag'"* ]]
}
