#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: cpu default" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_cpu_default.json \
      -s test_data/test_cpu_default-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: cpu defaultrequest missing" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_cpu_defaultrequest_missing.json \
      -s test_data/test_cpu_defaultrequest_missing-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"You are missing 'defaultRequest': 'cpu'"* ]]
}
