#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid decryption provider" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_decryption_provider.json \
      -s test_data/test_valid_decryption_provider-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid decryption provider" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_decryption_provider.json \
      -s test_data/test_invalid_decryption_provider-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The Kustomization 'example' Spec.decryption.provider must be set to one of [sops mozilla-sops]; found 'invalid-provider'"* ]]
}
