#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid storage namespace" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_storage_namespace.json \
      -s test_data/test_valid_storage_namespace-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid storage namespace" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_storage_namespace.json \
      -s test_data/test_invalid_storage_namespace-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The HelmRelease 'invalid-helm-release' storageNamespace must be one of the allowed storage namespaces; found 'disallowed-storage-namespace'"* ]]
}
