#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: var substitution disabled" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_var_substitution_disabled.json \
      -s test_data/test_var_substitution_disabled-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: var substitution enabled" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_var_substitution_enabled.json \
      -s test_data/test_var_substitution_enabled-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The Kustomization 'example' spec.postBuild.substitute.var_substitution_enabled must be disabled"* ]]
}
