#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: predefined media and operation" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_predefined_media_and_operation.json \
      -s test_data/test_predefined_media_and_operation-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: non predefined media" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_non_predefined_media.json \
      -s test_data/test_non_predefined_media-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The OCIRepository 'example' has a non-predefined media type. Found: 'application/non-predefined.media'"* ]]
}
