#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid case" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_case.json \
      -s test_data/test_valid_case-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid pod" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_pod.json \
      -s test_data/test_invalid_pod-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"Workloads must not be running in the namespace 'default'; found 'default'"* ]]
}
