#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid cluster role" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_cluster_role.json \
      -s test_data/test_valid_cluster_role-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid cluster role" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_cluster_role.json \
      -s test_data/test_invalid_cluster_role-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"Resource 'secrets' must not contain the verb 'list'; found resource '[secrets]' with verbs '[list]'"* ]]
}
