#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid path" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_path.json \
      -s test_data/test_valid_path-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: excluded path" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_excluded_path.json \
      -s test_data/test_excluded_path-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The Kustomization 'example' spec.path '/forbidden' is not allowed."* ]]
}
