#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid service account name" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_service_account_name.json \
      -s test_data/test_valid_service_account_name-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid service account name" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_service_account_name.json \
      -s test_data/test_invalid_service_account_name-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The HelmRelease 'invalid-helm-release' serviceAccountName must contain a value from parameters.service_account_names; found 'invalid-sa'"* ]]
}
