[package]
name = "env-variable-secrets-scanner-policy"
version = "1.0.16"
authors = ["raulcabello <raul.cabello@suse.com>"]
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.23.0"
encoding = "0.2.33"
k8s-openapi = { workspace = true }
kubewarden-policy-sdk = { workspace = true }
rusty_hog_scanner = { rev = "9da595ad204f017cff576ffac5bce7f2bed1be2f", git = "https://github.com/newrelic/rusty-hog/" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
