#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: existing security context" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_existing_security_context.json \
      -s test_data/test_existing_security_context-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: missing security context" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_missing_security_context.json \
      -s test_data/test_missing_security_context-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"Container missing spec.template.spec.containers[0].securityContext while Pod spec.template.spec.securityContext is not defined as well., Container missing spec.template.spec.containers[1].securityContext while Pod spec.template.spec.securityContext is not defined as well."* ]]
}
