#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: correct branch" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_correct_branch.json \
      -s test_data/test_correct_branch-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: wrong branch" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_wrong_branch.json \
      -s test_data/test_wrong_branch-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The GitRepository 'example' must reference the specific branch 'main'. Found: 'dev'"* ]]
}
