#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: not latest tag" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_not_latest_tag.json \
      -s test_data/test_not_latest_tag-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: latest tag" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_latest_tag.json \
      -s test_data/test_latest_tag-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The OCIRepository 'example' should not use 'latest' as a tag reference."* ]]
}
