#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid rollback disabled" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_rollback_disabled.json \
      -s test_data/test_valid_rollback_disabled-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid rollback enabled" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_rollback_enabled.json \
      -s test_data/test_invalid_rollback_enabled-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The HelmRelease rollback must be disabled; some rollback options are enabled."* ]]
}
