#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: allowed port" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_allowed_port.json \
      -s test_data/test_allowed_port-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: prohibited port" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_prohibited_port.json \
      -s test_data/test_prohibited_port-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"Container should not expose port 22"* ]]
}
