#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid no post renderer" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_no_post_renderer.json \
      -s test_data/test_valid_no_post_renderer-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid post renderer enabled" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_post_renderer_enabled.json \
      -s test_data/test_invalid_post_renderer_enabled-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The HelmRelease 'invalid-helm-release' must not have post-renderers enabled."* ]]
}
