#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid install retries" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_install_retries.json \
      -s test_data/test_valid_install_retries-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid lower bound upgrade retries" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_lower_bound_upgrade_retries.json \
      -s test_data/test_invalid_lower_bound_upgrade_retries-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The HelmRelease 'invalid-helm-release' upgrade remediation retries must be between 3 and 5; found 2"* ]]
}
