#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: limits cpu" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_limits_cpu.json \
      -s test_data/test_limits_cpu-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: limits cpu missing" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_limits_cpu_missing.json \
      -s test_data/test_limits_cpu_missing-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"You are missing 'limits.cpu'"* ]]
}
