#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: allowed image" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_allowed_image.json \
      -s test_data/test_allowed_image-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: prohibited image" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_prohibited_image.json \
      -s test_data/test_prohibited_image-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"These images should be blocked: '[demoservice]'; found 'demoservice:latest', These images should be blocked: '[demoservice]'; found 'demoservice:v0.0.2'"* ]]
}
