#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: valid max history" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_valid_max_history.json \
      -s test_data/test_valid_max_history-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: invalid max history" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_invalid_max_history.json \
      -s test_data/test_invalid_max_history-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"The HelmRelease 'invalid-helm-release' maxHistory cannot exceed 10; found 15"* ]]
}
