#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

# TODO: this policy needs a hand-written counter-case.

@test "reject: container sysctls" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_container_sysctls.json \
      -s test_data/test_container_sysctls-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"Adding sysctls could lead to unauthorized escalated privileges to the underlying node"* ]]
}
