name: Release drafter auto labeler

on:
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read

jobs:
  auto_labeler:
    permissions:
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@3a7fb5c85b80b1dda66e1ccb94009adbbd32fce3 # v7.0.0
        with:
          config-name: "release-drafter.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
