#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: key value exists" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_key_value_exists.json \
      -s test_data/test_key_value_exists-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: snapshot class wrong" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_snapshot_class_wrong.json \
      -s test_data/test_snapshot_class_wrong-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"VolumeSnapshotClassName names should be 'csi-hostpath-snapclass', detected 'another-snapclass'"* ]]
}
