#!/usr/bin/env bats

# Generated by hack/generate-rego-e2e.py. Do not edit by hand.

@test "accept: owner exists" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_owner_exists.json \
      -s test_data/test_owner_exists-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject: owner missing" {
  run kwctl run -e gatekeeper annotated-policy.wasm \
      -r test_data/test_owner_missing.json \
      -s test_data/test_owner_missing-settings.json

  # this prints the output when one of the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [[ "$output" == *"you are missing a label with the key 'owner'"* ]]
}
